---
name: Data-Tabulate-Plugin-ASCIITable
version: 0.01
author:
  - 'Renee Baecker <module@renee-baecker.de>'
abstract: 'generate ASCII tables with C<Data::Tabulate>'
license: perl
build_requires:
  Test::CheckManifest: 1
  Test::More: 0
  Text::ASCIITable: 0.17
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  Data::Tabulate::Plugin::ASCIITable:
    file: lib/Data/Tabulate/Plugin/ASCIITable.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
