---
abstract: 'generate ASCII tables with Data::Tabulate '
author:
  - 'Renee Baecker <reneeb@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.132830'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-Tabulate-Plugin-ASCIITable
requires:
  Test::CheckManifest: '1.0'
  Text::ASCIITable: '0.20'
resources:
  bugtracker: http://github.com/reneeb/Data-Tabulate-Plugin-ASCIITable/issues
  homepage: http://github.com/reneeb/Data-Tabulate-Plugin-ASCIITable
  repository: http://github.com/reneeb/Data-Tabulate-Plugin-ASCIITable.git
version: '0.02'
